In [4]:
import numpy as np 
arr1=np.array([1,2,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 4 5 6]
<class 'numpy.ndarray'>
(5,)


In [9]:
#1_D array
arr2=np.array([1,2,4,5,6])
arr2.reshape((1,5))##1-row and 5-column



array([[1, 2, 4, 5, 6]])

In [14]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2.shape)
# arr2.reshape(2,5)
# print(arr2)
print(arr2)


(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
np.arange(0,10,2).reshape(5,1)
# print(a)

array([[0],
       [2],
       [4],
       [6],
       [8]])