In [4]:
import numpy as np 
arr1=np.array([1,2,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 4 5 6]
<class 'numpy.ndarray'>
(5,)


In [9]:
#1_D array
arr2=np.array([1,2,4,5,6])
arr2.reshape((1,5))##1-row and 5-column



array([[1, 2, 4, 5, 6]])

In [14]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2.shape)
# arr2.reshape(2,5)
# print(arr2)
print(arr2)


(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
np.arange(0,10,2).reshape(5,1)
# print(a)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
##indentiy meatrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
## attributes
arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimension:",arr.ndim)
print("Size(number of elements):",arr.size)
print("Data Type:",arr.dtype)
print("Item size(in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension: 2
Size(number of elements): 6
Data Type: int32
Item size(in bytes): 4


In [30]:
##numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## elements wise addition
print("Addition",arr1+arr2)

Addition [ 10  40  90 160 250]


In [ ]:
##