In [17]:
import numpy as np 
arr=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]])
print('Array:\n',arr)
print(arr[0][0])
print(arr[1:,1:])
print(arr[0:2,2:])
print(arr[0:2,:2])
print(type(arr))



Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[ 6  7  8]
 [10 11 12]]
[[3 4]
 [7 8]]
[[1 2]
 [5 6]]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
arr=np.array([4,5,6,7],float)
print(arr)

[4. 5. 6. 7.]


In [19]:
import numpy as np
import time


python_list = list(range(1000000))


numpy_array = np.array(python_list)


start = time.time()
python_result = [x * 2 for x in python_list]
print("Python List Time:", time.time() - start)

start = time.time()
numpy_result = numpy_array * 2
print("NumPy Array Time:", time.time() - start)


Python List Time: 0.08794140815734863
NumPy Array Time: 0.002419710159301758
