In [5]:
import numpy as np 
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
import numpy as np 
print(np.ones((4,5)))# used in Deep Learning and Machine Learning for weighted matrix

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
import numpy as np 
arr=np.array(
    [
        [3,4,5,6],
        [7,8,9,10],
        [12,13,14,15],
    ]
)
print(arr[1:,:1])
print(arr[1:,1:3])
arr[0,0]=100
arr[1:]=111
arr[:1]=0
print(arr)

[[ 7]
 [12]]
[[ 8  9]
 [13 14]]
[[  0   0   0   0]
 [111 111 111 111]
 [111 111 111 111]]


In [28]:
import numpy as np 
arr=np.eye(4,k=-2)
# ar1=np.indentity(6)
ar1=np.zeros((5,6))
print(arr)
print(ar1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [6]:
n=int(input("Enter a number"))
for i in range(11):
    print(f"{n} X {i}={n*i}")

11 X 0=0
11 X 1=11
11 X 2=22
11 X 3=33
11 X 4=44
11 X 5=55
11 X 6=66
11 X 7=77
11 X 8=88
11 X 9=99
11 X 10=110


In [13]:
##practical 
## 
# normalization{to have a mean of 0 and standard deviation}
import numpy as np 
data=np.array([1,2,3,4,5])

mean=np.mean(data)
std_dev=np.std(data)

normalized_data=(data-mean)/std_dev
print("Normalized data:",normalized_data)


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
